### ISSUE TITLE
Decompile does not create 'activitymodifier' $sequence command

### ISSUE THREAD

**Issue by Petercov** [ZeqMacaw/Crowbar#1]

**Comment by ZeqMacaw** [comment]
For which models does Crowbar fail to decompile activitymodifier?

**Comment by Petercov** [comment]
I compiled a model using this command, verified that the command functioned, then decompiled the model.

**Comment by ZeqMacaw** [comment]
Which game's studiomdl did you you use to compile the model?

**Comment by Petercov** [comment]
Source SDK Base 2013 Multiplayer.

**Comment by ZeqMacaw** [comment]
Fixed in Crowbar 0.68.
