### ISSUE TITLE
Requesting Gmod 64 bit gmad.exe and gmpublish.exe support :)

### ISSUE THREAD

**Issue by CryptAlchemy** [ZeqMacaw/Crowbar#10]
Hi there!
First of all, I love your Crowbar tool and I think it really changes the game when it comes to making things for various Steam games including Gmod!

I'd like to request support for the 64-bit versions of gmad.exe and gmpublish.exe.

In Garry's Mod, for example, the two 64-bit tools are located in the `win64` subfolder of the `bin` folder.

The regular 32-bit tools located in the `bin` folder are very slow and take forever; they also don't like large addons.

It would be awesome if you could do one of the following:
a) Select the version of gmad.exe and gmpublish.exe; I know that you can select gmad.exe in "Set Up Games" but that doesn't change anything when it comes to publishing because it still runs the 32-bit version under `bin`.
b) Automatically detect if the `win64` folder is available and use those gmad.exe and gmpublish.exe tools in there. (would be significantly easier to implement than Option A).

Thanks and nice work!

**Comment by ZeqMacaw** [comment]
This looks like a good idea, and I will look into this when I get back to working on Crowbar this fall.

**Comment by ZeqMacaw** [comment]
Done in: https://github.com/ZeqMacaw/Crowbar/releases/tag/v0.72
