### ISSUE TITLE
Requesting support for the second UV channel from CSGO FBX mdls (feature request)

### ISSUE THREAD

**Issue by Squinkz** [ZeqMacaw/Crowbar#12]
Since the Nuke update a few years back, CSGO has had the ability to compile FBX models using a second UV channel.

Unfortunately decompilation only decompiles to SMD which does not support a second UV channel.
Would be fantastic if there was an option to decompile back to FBX, or to possibly select which UV channel to preserve when decompiling to SMD.

Thanks for the great work!

**Comment by ZeqMacaw** [comment]
I'll put it on the ToDo list and see what I can do.

:)

**Comment by ZeqMacaw** [comment]
Fixed in: https://github.com/ZeqMacaw/Crowbar/releases/tag/v0.72
