### ISSUE TITLE
linux?

### ISSUE THREAD

**Issue by Idiot64** [ZeqMacaw/Crowbar#13]
please, doesn't work well under wine

**Comment by ZeqMacaw** [comment]
I am not likely to develop Crowbar for Linux; I simply do not have the time to spend on it. 

Maybe someone else can take the core code and write a nice Linux interface for it.

**Comment by Idiot64** [comment]
ok thanks

**Comment by RowanTL** [comment]
Fable 5 and vibe coding is a wonderful thing. I (Fable 5) made a nix flake for any of those who are super nerd. I only tried decompiling (but ended up not needing it any way). Unpack crashes on opening the tab. I haven't tried the others.

For those who may see any amount of use from this in the future: [https://github.com/RowanTL/Crowbar-nix](https://github.com/RowanTL/Crowbar-nix)
