### ISSUE TITLE
CSGO not closing if you run the game throughout View tab.

### ISSUE THREAD

**Issue by GXP10** [ZeqMacaw/Crowbar#14]
Hi there.
for some reason, after you quit csgo, the game itself didn't close it properly which making it impossible to relaunch the game up again.

the only way to close is that you needs to quit the game then close the tool and relaunch it again or using task manager to force close csgo.

**Comment by ZeqMacaw** [comment]
CSGO currently seems to require a different way to start it than other Source-engine games. Crowbar 0.71 can not open the game anymore. 

Thus, this bug is no longer relevant. Closing issue, but will consider how to open CSGO game a different way later.
