### ISSUE TITLE
Decompiles seem to fail on large animation counts

### ISSUE THREAD

**Issue by ZooLSmith** [ZeqMacaw/Crowbar#17]
There seems to be a regression on decompiles, as of 0.68, some QC files will be cut, I've tested with 0.62 and it works fine there.

The log looks fine on newer versions but the file is cut, I'm only getting 16KB/331 lines of data for a file that used to be 526KB/12026 lines.

The file I'm testing this on is animset_t.mdl from CS:GO located in models/player/custom_player/

It cuts near the end of one of the weightlists and seems to have doubled the last entry.

```
$weightlist "weights_strafe" {
	 "pelvis" 0.8
	 "lean_root" 0
	 "cam_driver" 0
         ...
	 "leg_upper_R_TWIST" 1
	 "leg_upper_R_TWIST1" 1
	 "lfoot_lock" 1
	 "rfoot_lock" 1
	 "lh_ik_driver" 0
	 "ValveBiped.weapon_bone" 0
	 "ValveBiped.weapon_bone" 0
```

I'm using an older version for now, but this only seems to affect models with a lot of animations, I didn't had issues with it on other models.

**Comment by ZeqMacaw** [comment]
Fixed in: https://github.com/ZeqMacaw/Crowbar/releases/tag/v0.72
