### ISSUE TITLE
Decompile does not create 'is_boing' $jigglebone property group

### ISSUE THREAD

**Issue by Petercov** [ZeqMacaw/Crowbar#2]
Used on models\props_gameplay\ball001.mdl in Team Fortress 2.

**Comment by ZeqMacaw** [comment]
How do you know "is_boing" is supposed to be in there? I have never seen this option anywhere.

**Comment by Petercov** [comment]
This and #1 deal with, until now, undocumented features of model versions v48(2013 variant) and v49 (at least).

**Comment by ZeqMacaw** [comment]
Stating "undocumented" features does not prove the option exists.

**Comment by Petercov** [comment]
I found evidence of their existence in the sdk's c++ header files, I text searched the studiomdl executable for command names, and then I tested the commands. You can verify by searching Source SDK Base 2013 Multiplayer's studiomdl.exe for 'is_boing' in a text editor.

**Comment by ZeqMacaw** [comment]
Okay, that is what I can use. Thanks.
