### ISSUE TITLE
Another weird physics issue

### ISSUE THREAD

**Issue by Species3259** [ZeqMacaw/Crowbar#22]
Model : item_dropper_128 (props_ingame in portal2_dlc2 VPK)

BEFORE : decompile
AFTER : rename - compile - decompile

I like my cubes to drop from above the dropper model instead of spawning them in plain sight in the dropper.
No problem with the ingame model. Iris opens, cube spawns and drops all the way down.
You can see from the physics model that this poses no issues.

![image](https://user-images.githubusercontent.com/33939468/165818468-6f61dfba-c130-4dbc-9624-3a3b9f1a1e6d.png)

Then i rename the model (item_dropperxx_128) and compile and try to use it ingame.

![image](https://user-images.githubusercontent.com/33939468/165818670-b052b793-ed35-4272-90c8-19fcac19c742.png)

You can see from the (decompiled) item_dropperxx_128 model that NOW i have a problem.

Clearly the cube cant fall through the dropper any longer. It stays on the top.
Workaround is to make the model non-solid, create a func_clip_vphysics and use triggers to disable/enable in order to mimic solidity of the dropper.

And there is some weird stuff in the QC when decompiling.

This is after decompiling the item_dropper_128 👍 

![image](https://user-images.githubusercontent.com/33939468/165819748-e793f3fd-8879-423e-90b7-703ca67eac5f.png)

Although it is possible that this is the name Valve used it seems a bit sus :-)

And then this after renaming the model (item_dropperxx_128), then compile and decompile.

![image](https://user-images.githubusercontent.com/33939468/165820044-5606ec66-910b-4b6a-bf47-f2bc6201caa4.png)

Now i know there is something not right...

**Comment by ZeqMacaw** [comment]
Closing this issue, because this was fixed in 0.72, probably when Issue #18 was merged in.

The weird naming of bodygroup mesh file probably shows when you use the Decompile option "Prefix mesh file names with model name".
