### ISSUE TITLE
Drag and Drop from Crowbar causes Windows Explorer to freeze

### ISSUE THREAD

**Issue by baesik** [ZeqMacaw/Crowbar#23]
It only causes this issue when you drag a file from Crowbar's unpacking tab to any windows explorer window/folder. It does not have this problem if I drag the files/folder directly to the desktop.

**Comment by ZeqMacaw** [comment]
I have not been able to reproduce this problem, nor has anyone else reported this problem. It seems like this was a problem with File Explorer -- perhaps it was only a one-time event due to something else that Windows was doing at the time.
