### ISSUE TITLE
ValveBiped.bip01_Pelvis has a rotation constraint but no parent

### ISSUE THREAD

**Issue by alinanonymous** [ZeqMacaw/Crowbar#28]
Keep getting this error after compiling a model. This happens on models that I've already compiled as well, then decompiled, and tried to compile again. I wish I knew what this meant, as I can't think of what would be considered a "rotation constraint" by crowbar. It's too vague. Here's the log:
[monoko compile-log.txt](https://github.com/ZeqMacaw/Crowbar/files/9293178/monoko.compile-log.txt)

**Comment by alinanonymous** [comment]
It's also possible that this could just be an error created by blender Source tools, but due to the vague error I have no way of telling.

**Comment by ZeqMacaw** [comment]
Crowbar does NOTHING with compiling; it is simply a front-end to the model compiler in the game files. Thus, this is not a good place for getting help with model compile errors.

I suggest getting help in the Dead4Mods discord in its #modding channel: https://discord.gg/4qtmzBP
