### ISSUE TITLE
False Positive when downloading crowbar

### ISSUE THREAD

**Issue by FunkyPixie** [ZeqMacaw/Crowbar#31]
When I download crowbar windows defender (yes i use that) sends me a notification that says it found a piece of malware called contebrew.A!ml...

![dd1c5fe8985f489645902ed81c465fc3](https://user-images.githubusercontent.com/5890200/190874123-b5af6c90-3646-4560-aa53-c9f6fbbf61a2.png)

**Comment by ZeqMacaw** [comment]
Although I know I do not write virus or malware, I wanted to double-check the file myself with Windows Defender. 

I recently reinstalled the latest WIndows 10 Pro (22H2) and scanned the mentioned file with Microsoft Defender (the name keeps changing). Results: No current threats.
