### ISSUE TITLE
'EXCEPTION_ACCESS_VIOLATION' (assert: 1)

### ISSUE THREAD

**Issue by karlupo** [ZeqMacaw/Crowbar#39]
I tried to decompile a model and compile it again and following error comes up: 'EXCEPTION_ACCESS_VIOLATION' (assert: 1).

Could someone pls help?

Here is the full log: 

Compiling with Crowbar 0.72: "C:\Users\karlu\OneDrive\Desktop\tester\212th_airborne2_parjai.qc" ...

  Compiling "212th_airborne2_parjai.qc" ...
    Output from compiler "C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\bin\studiomdl.exe": 
      qdir:    "c:\users\karlu\onedrive\desktop\tester\"
      gamedir: "C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\"
      g_path:  "212th_airborne2_parjai.qc"
      Building binary model files...
      Working on "212th_airborne2_parjai.qc"
      SMD MODEL body.smd
      SMD MODEL body_upper.smd
      SMD MODEL body_lower.smd
      SMD MODEL helmet.smd
      SMD MODEL face.smd
      SMD MODEL macrobinoculars_up.smd
      SMD MODEL macrobinoculars.smd
      SMD MODEL pauldron.smd
      SMD MODEL pauldron_strap.smd
      SMD MODEL pauldron_ammo.smd
      SMD MODEL grey_pauldron.smd
      SMD MODEL ganch_pauldron.smd
      SMD MODEL strap.smd
      SMD MODEL fordo_pauldron.smd
      SMD MODEL gunstrap.smd
      SMD MODEL suspenders.smd
      SMD MODEL suspenders_ammo.smd
      SMD MODEL kama.smd
      SMD MODEL tag_antenna.smd
      SMD MODEL holsters.smd
      SMD MODEL holsters_right.smd
      SMD MODEL holsters_dc17.smd
      SMD MODEL holsters_right_dc17.smd
      SMD MODEL rangefinder_up.smd
      SMD MODEL rangefinder.smd
      SMD MODEL jetpack.smd
      SMD MODEL bag.smd
      SMD MODEL sidebag.smd
      SMD MODEL ammo_shoulder.smd
      SMD MODEL ammo_arm.smd
      SMD MODEL tag_antenna_2.smd
      SMD MODEL back_ammo.smd
      SMD MODEL rank_tab.smd
      Marking bone L_Calf_Jiggle as a jiggle bone
      Marking bone R_Calf_Jiggle as a jiggle bone
      SMD MODEL 212th_airborne2_parjai_anims\ragdoll.smd
      SMD MODEL 212th_airborne2_parjai_physics.smd
      Processing LOD for material: gloves
      Processing LOD for material: 501st_fabric
      Processing LOD for material: 501st_body
      Processing LOD for material: 501st_body
      Processing LOD for material: 501st_body_airborne
      Processing LOD for material: 501st_body
      Processing LOD for material: 501st_body_airborne
      Processing LOD for material: 2nd_helmet
      Processing LOD for material: 501st_face
      Processing LOD for material: 501st_eyes
      Processing LOD for material: 501st_teeth
      Processing LOD for material: 501st_specialist
      Processing LOD for material: 501st_specialist
      Processing LOD for material: 501st_specialist
      Processing LOD for material: 501st_specialist
      Processing LOD for material: 501st_heavy
      Processing LOD for material: 501st_specialist
      Processing LOD for material: arc_ct_gear
      Processing LOD for material: 501st_grey_pauldron
      Processing LOD for material: 501st_ganch_pauldron
      Processing LOD for material: 501st_heavy
      Processing LOD for material: fordo_heavy
      Processing LOD for material: fordo_pauldron
      Processing LOD for material: 501st_gunstrap
      Processing LOD for material: 501st_suspenders
      Processing LOD for material: 501st_heavy
      Processing LOD for material: 501st_rex_pauldron
      Processing LOD for material: 501st_heavy
      Processing LOD for material: tag_antenna
      Processing LOD for material: 501st_gear
      Processing LOD for material: 501st_gear
      Processing LOD for material: leg_holsters
      Processing LOD for material: dc-17-pistol
      Processing LOD for material: leg_holsters
      Processing LOD for material: dc-17-pistol
      Processing LOD for material: rex_rangefinder
      Processing LOD for material: rex_rangefinder
      Processing LOD for material: arc_ct_jetpack
      Processing LOD for material: 501st_heavy
      Processing LOD for material: 501st_heavy
      Processing LOD for material: 501st_heavy
      Processing LOD for material: 501st_specialist
      Processing LOD for material: tag_antenna
      Processing LOD for material: 501st_gear
      Processing LOD for material: rank_tab
      Processing jointed collision model
      ValveBiped.Bip01_Pelvis  (122 verts, 1 convex elements) volume: 486.60
      ValveBiped.Bip01_L_Thigh (119 verts, 1 convex elements) volume: 481.93
      ValveBiped.Bip01_L_Calf  (116 verts, 1 convex elements) volume: 365.51
      ValveBiped.Bip01_L_Foot  ( 96 verts, 1 convex elements) volume: 80.63
      ValveBiped.Bip01_L_Toe0  ( 40 verts, 1 convex elements) volume: 22.30
      ValveBiped.Bip01_R_Thigh (119 verts, 1 convex elements) volume: 481.94
      ValveBiped.Bip01_R_Calf  (116 verts, 1 convex elements) volume: 365.53
      ValveBiped.Bip01_R_Foot  ( 96 verts, 1 convex elements) volume: 80.63
      ValveBiped.Bip01_R_Toe0  ( 40 verts, 1 convex elements) volume: 22.31
      ValveBiped.Bip01_Spine   (118 verts, 1 convex elements) volume: 224.42
      ValveBiped.Bip01_Spine2  (129 verts, 1 convex elements) volume: 688.70
      ValveBiped.Bip01_Neck1   ( 68 verts, 1 convex elements) volume: 47.88
      ValveBiped.Bip01_Head1   (121 verts, 1 convex elements) volume: 373.63
      ValveBiped.Bip01_R_Clavicle ( 90 verts, 1 convex elements) volume: 73.43
      ValveBiped.Bip01_R_UpperArm ( 92 verts, 1 convex elements) volume: 96.22
      ValveBiped.Bip01_R_Forearm ( 70 verts, 1 convex elements) volume: 70.99
      ValveBiped.Bip01_R_Hand  ( 48 verts, 1 convex elements) volume: 27.69
      ValveBiped.Bip01_L_Clavicle ( 89 verts, 1 convex elements) volume: 74.11
      ValveBiped.Bip01_L_UpperArm ( 92 verts, 1 convex elements) volume: 96.22
      ValveBiped.Bip01_L_Forearm ( 70 verts, 1 convex elements) volume: 70.99
      ValveBiped.Bip01_L_Hand  ( 48 verts, 1 convex elements) volume: 27.69
      Collision model completed.
      ---------------------
      writing C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\models/starwars\grady\212th_airborne\212th_airborne2_parjai.mdl:
      bones        27764 bytes (98)
         animation       x       y       ips    angle
          @ragdoll    0.00    0.00 :    0.00 (   0.00) 7.2
      animations    7464 bytes (1 anims) (217 frames) [0:07]
      sequences      608 bytes (1 seq) 
      ik/pose       8104 bytes
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      eyeballs         0 bytes (0 eyeballs)
      flexes           0 bytes (0 flexes)
      textures      1660 bytes
      keyvalues       20 bytes
      bone transforms    13392 bytes
      bone flex driver       0 bytes
      Collision model volume 4259.36 in^3
      collision        0 bytes
      total        67220
      ---------------------
      writing C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\models/starwars\grady\212th_airborne\212th_airborne2_parjai.vvd:
      vertices    613248 bytes (12776 vertices)
      vertices    360096 bytes (7502 vertices)
      vertices    379488 bytes (7906 vertices)
      vertices    267312 bytes (5569 vertices)
      vertices    283296 bytes (5902 vertices)
      vertices     99648 bytes (2076 vertices)
      vertices    100080 bytes (2085 vertices)
      vertices    103920 bytes (2165 vertices)
      vertices    302448 bytes (6301 vertices)
      vertices    110112 bytes (2294 vertices)
      vertices     47616 bytes (992 vertices)
      vertices     89184 bytes (1858 vertices)
      vertices    255744 bytes (5328 vertices)
      vertices    230784 bytes (4808 vertices)
      vertices     22320 bytes (465 vertices)
      vertices     30720 bytes (640 vertices)
      vertices     58848 bytes (1226 vertices)
      vertices    184416 bytes (3842 vertices)
      vertices     18336 bytes (382 vertices)
      vertices     45984 bytes (958 vertices)
      vertices     22992 bytes (479 vertices)
      vertices    129696 bytes (2702 vertices)
      vertices     64848 bytes (1351 vertices)
      vertices     15168 bytes (316 vertices)
      vertices     15168 bytes (316 vertices)
      vertices    277968 bytes (5791 vertices)
      vertices     73008 bytes (1521 vertices)
      vertices    116496 bytes (2427 vertices)
      vertices    237792 bytes (4954 vertices)
      vertices     28704 bytes (598 vertices)
      vertices     18336 bytes (382 vertices)
      vertices    106176 bytes (2212 vertices)
      vertices     31920 bytes (665 vertices)
      tangents    204416 bytes (12776 vertices)
      tangents    120032 bytes (7502 vertices)
      tangents    126496 bytes (7906 vertices)
      tangents     89104 bytes (5569 vertices)
      tangents     94432 bytes (5902 vertices)
      tangents     33216 bytes (2076 vertices)
      tangents     33360 bytes (2085 vertices)
      tangents     34640 bytes (2165 vertices)
      tangents    100816 bytes (6301 vertices)
      tangents     36704 bytes (2294 vertices)
      tangents     15872 bytes (992 vertices)
      tangents     29728 bytes (1858 vertices)
      tangents     85248 bytes (5328 vertices)
      tangents     76928 bytes (4808 vertices)
      tangents      7440 bytes (465 vertices)
      tangents     10240 bytes (640 vertices)
      tangents     19616 bytes (1226 vertices)
      tangents     61472 bytes (3842 vertices)
      tangents      6112 bytes (382 vertices)
      tangents     15328 bytes (958 vertices)
      tangents      7664 bytes (479 vertices)
      tangents     43232 bytes (2702 vertices)
      tangents     21616 bytes (1351 vertices)
      tangents      5056 bytes (316 vertices)
      tangents      5056 bytes (316 vertices)
      tangents     92656 bytes (5791 vertices)
      tangents     24336 bytes (1521 vertices)
      tangents     38832 bytes (2427 vertices)
      tangents     79264 bytes (4954 vertices)
      tangents      9568 bytes (598 vertices)
      tangents      6112 bytes (382 vertices)
      tangents     35392 bytes (2212 vertices)
      tangents     10640 bytes (665 vertices)
      total      6322560 bytes
      ---------------------
      Generating optimized mesh "C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\models/starwars\grady\212th_airborne\212th_airborne2_parjai.sw.vtx":
      body parts:       152 bytes
      models:          1000 bytes
      model LODs:       600 bytes
      meshes:           405 bytes
      strip groups:    1125 bytes
      strips:          1215 bytes
      verts:         889101 bytes
      indices:       711858 bytes
      bone changes:       8 bytes
      everything:   1604900 bytes
      ---------------------
      Generating optimized mesh "C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\models/starwars\grady\212th_airborne\212th_airborne2_parjai.dx80.vtx":
      body parts:       152 bytes
      models:          1000 bytes
      model LODs:       600 bytes
      meshes:           405 bytes
      strip groups:    1125 bytes
      strips:          1404 bytes
      verts:         893043 bytes
      indices:       711858 bytes
      bone changes:    2400 bytes
      everything:   1611423 bytes
      ---------------------
      Generating optimized mesh "C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\models/starwars\grady\212th_airborne\212th_airborne2_parjai.dx90.vtx":
      body parts:       152 bytes
      models:          1000 bytes
      model LODs:       600 bytes
      meshes:           405 bytes
      strip groups:    1125 bytes
      strips:          1215 bytes
      verts:         889101 bytes
      indices:       711858 bytes
      bone changes:    2024 bytes
      everything:   1606916 bytes
      ERROR: 'EXCEPTION_ACCESS_VIOLATION' (assert: 1)
      ERROR: Aborted Processing on 'starwars\grady\212th_airborne\212th_airborne2_parjai.mdl'
    CROWBAR: Deleted empty temporary compile folder "C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\models".
  ... Compiling "212th_airborne2_parjai.qc" finished. Check above for any errors.

... Compiling with Crowbar 0.72: "C:\Users\karlu\OneDrive\Desktop\tester\212th_airborne2_parjai.qc" finished.

**Comment by ZeqMacaw** [comment]
This is not a Crowbar issue. 

The model must have been compiled with a different compiler than the Garry's Mod one you used via Crowbar.

**Comment by karlupo** [comment]
Thank you for your fast answer. Which compiler for example?

**Comment by ZeqMacaw** [comment]
Sorry. If I knew, I would have told you in my first post.

**Comment by karlupo** [comment]
Update: If I delete some bodygroups it suddendly works. Is there a way to increase the max ammount of bodygroups/vertecies a model can have?

**Comment by Feromon32** [comment]
Use sfm compiler and add $maxverts 999999 to qc file, after $modelname,
