### ISSUE TITLE
Crowbar's Pack tab uses relative path where absolute one is required.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [ZeqMacaw/Crowbar#5]
I'm trying to pack a Garry's Mod addon using Crowbar and it doesn't work, because GMAD expects an absolute path to the input folder.

![](https://user-images.githubusercontent.com/5104603/68172645-5bf69580-ff89-11e9-9507-6ada12345975.png)

The `addon.json` file exists in this directory and dragging the folder to gmad.exe directly works fine.

**Comment by ZeqMacaw** [comment]
Thanks for the bug report. I will fix this for next release.

**Comment by ZeqMacaw** [comment]
I am unable to reproduce this bug, even after trying folder paths and names like what the screenshot shows.

Maybe the addon.json file was opened in another tool at the time you saw the error.

I am not sure what else to try.

**Comment by YuRaNnNzZZ** [comment]
I'm sorry, it's just me being dumb. I didn't notice that i was using a parent folder of an addon i wanted to pack.
