### ISSUE TITLE
Weird order of actions in "Download" section

### ISSUE THREAD

**Issue by maxim-fedotov-1997** [ZeqMacaw/Crowbar#6]
Version of Crowbar: 0.63
-----------
Now, I'm not sure what goes wrong with this, but I find it that this is not how it (probably) should work.
If GMod's addon is downloaded while "*Convert to expected file or folder*" is on, this happens...
```
Getting item content download link.
Item content download link found. Downloading file via web.
Downloading workshop item as: "F:\ProjectAlivefromashes\WorkOnConversionOfRagdollBase\Crowbar_decompiler\crowbar_downloads\Saurina_Wolf_Mollendorf_pony_OC_1566827563_2534032951_2019-08-26-2053.gma"
Download complete.
Downloaded file: "F:\ProjectAlivefromashes\WorkOnConversionOfRagdollBase\Crowbar_decompiler\crowbar_downloads\Saurina_Wolf_Mollendorf_pony_OC_1566827563_2534032951_2019-08-26-2053.gma"
Decompressing downloaded Garry's Mod workshop file into a GMA file.
Decompress done.
Deleted: "F:\ProjectAlivefromashes\WorkOnConversionOfRagdollBase\Crowbar_decompiler\crowbar_downloads\Saurina_Wolf_Mollendorf_pony_OC_1566827563_2534032951_2019-08-26-2053.gma"
Final file: "F:\ProjectAlivefromashes\WorkOnConversionOfRagdollBase\Crowbar_decompiler\crowbar_downloads\Saurina_Wolf_Mollendorf_pony_OC_1566827563_2534032951_2019-08-26-2053.gma"
```
![Imgur](https://i.imgur.com/9GK8SJj.png)
Upon checking the folder, I find that nothing changed, as the file that I was trying to get gets deleted in "cleanup" of the pre-conversion file.

If I do the same without that checkbox, though...
```
Getting item content download link.
Item content download link found. Downloading file via web.
Downloading workshop item as: "F:\ProjectAlivefromashes\WorkOnConversionOfRagdollBase\Crowbar_decompiler\crowbar_downloads\Saurina_Wolf_Mollendorf_pony_OC_1845972359_2019-08-26-2053.gma"
Download complete.
Downloaded file: "F:\ProjectAlivefromashes\WorkOnConversionOfRagdollBase\Crowbar_decompiler\crowbar_downloads\Saurina_Wolf_Mollendorf_pony_OC_1845972359_2019-08-26-2053.gma"
```
![Imgur](https://i.imgur.com/VRRjx9I.png)
Now it doesn't deletes the file, but without conversion, it's not useful, as now none of the GMA unpackers (including even Crowbar's own) can't see/do anything with it.

I'm not rushing at all, but I'd be thankful if it could be resolved.
Thanks for the program, though. :D

**Comment by ZeqMacaw** [comment]
Thanks for the detailed bug report. I apologize for the inconvenience.

The workaround is to use 7-Zip to decompress the unconverted file.

I have been aware of the bug and have already fixed it for next release.

**Comment by maxim-fedotov-1997** [comment]
Confirming bug being gone in 0.64. Issue closed. Thanks again! :D
