### ISSUE TITLE
Downloading several items from the Workshop causes friends to receive notification spam

### ISSUE THREAD

**Issue by KiwifruitDev** [ZeqMacaw/Crowbar#60]
## Description

I was downloading a collection through Crowbar and by doing so, I had a few different friends message me to stop launching games

I had Hammer++ for CSGO open, which caused my Steam presence to display `Counter-Strike: Global Offensive - SDK`.

Crowbar set my presence to `Garry's Mod`, which then reverted to `Source SDK` before finally being set back to `Counter-Strike: Global Offensive - SDK`.

## Images

![image](https://github.com/ZeqMacaw/Crowbar/assets/25839651/eaac9f10-a631-4043-8c11-1afdeaeb5e86)
![image](https://github.com/ZeqMacaw/Crowbar/assets/25839651/e83df9c3-e921-4c16-883b-d597d7967fad)
![image](https://github.com/ZeqMacaw/Crowbar/assets/25839651/9b00f5ca-3b12-4fc8-bb38-202913ce730c)

**Comment by ZeqMacaw** [comment]
This is a Steam issue, not a Crowbar issue. Any time a game accesses the game's workshop, Steam shows the game as open. Usually a game is already open when accessing its workshop (for subscriptions and publishing), so no new "opening game" notifications are sent. However, Crowbar must "pretend" to be a game to Steam for each download, so Steam sees a game "opening" for each download.

To workaround this, I set my Steam to "Invisible" before downloading (or publishing) via Crowbar.
