### ISSUE TITLE
Compiling messes up weights on bullets

### ISSUE THREAD

**Issue by DRAG4YOU** [ZeqMacaw/Crowbar#64]
I been trying to fix the reload animation of the Short Stop LODs and i seem to to have an issue with your compiler, this issue only appears on LOD1 bullets and bullet casings when you reload:

![SJqTB4X](https://github.com/ZeqMacaw/Crowbar/assets/16998974/01cc1841-8444-424d-b08c-23570fdec2b2)

This bug only seems to appear on LOD1 but its odd that even I when export the model and import the new models on blender the weights seem to be fine but once i compile the bug appears.

This is how the bullets and casings weights look on blender before compiling:

Bullets and Bullet Casings before compiling and importing them back just to check that they are correct:
![screen1](https://github.com/ZeqMacaw/Crowbar/assets/16998974/d0fb12d9-db60-4c94-a262-72ca407de7ea)
![screen2](https://github.com/ZeqMacaw/Crowbar/assets/16998974/f43f3d56-34ef-42c6-a0b4-afaaa5bac820)

And this is how they look once i compile and decompile them, then import them on blender:
![screen3](https://github.com/ZeqMacaw/Crowbar/assets/16998974/f0b350cb-2044-4932-9cc1-7c6e67261e42)
![screen4](https://github.com/ZeqMacaw/Crowbar/assets/16998974/ac6f5769-a9a8-490a-9e86-b72c5b340cb9)

The odd thing is that LOD0, LOD2 and LOD3 seem to be working fine but only LOD1 seems to have this issue.

I changed the bullets and bullets casing of LOD1 to LOD0 and this issue disappears but if i modify the polygonal number of the bullets and bullets casing of LOD0 to be the same as the ones from LOD1 the issue comes back.

The compiler seems to add weights on both vm_weapon_bone_1 and vm_weapon_bone_2 of both bullets and bullets casings of LOD1 for some reason. Can you please fix this? because i dont know what to do.

Also, here's my blender file and decompile file:
[Short Stop Fix WIP.zip](https://github.com/ZeqMacaw/Crowbar/files/13848736/Short.Stop.Fix.WIP.zip)

Just compile it and decompile it and you'll see what's going on.

**Comment by ZeqMacaw** [comment]
Based on your wording, this is a model compiler issue, not a Crowbar issue. Crowbar does not do any model compiling, but calls a game's model compiler.
