### ISSUE TITLE
Missing faces on decompile

### ISSUE THREAD

**Issue by CS-PRO1** [ZeqMacaw/Crowbar#8]
I'm using the latest 0.68 release, I tried to decompile and load a model but here's how it looked like:
![f](https://user-images.githubusercontent.com/50755959/77660916-9a194380-6f82-11ea-9d61-64c38e42ba31.jpg)
In HLMV the model is fine, but once decompiled the .smd files are broken.

Here's the model that caused the issue:
https://gamebanana.com/models/4386

**Comment by ZeqMacaw** [comment]
When I imported (into Blender) just the "c_hl_taucannon.smd" mesh file, I saw what bug report image shows. However, there are 5 other mesh SMD files that fill-in the rest of the model.

Closing this bug report.

**Comment by CS-PRO1** [comment]
Oh, I just realized that xd Sorry if this caused some trouble. I genuinely thought the other SMDs were the same main one chopped.
